name: Pose2Sim
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - console_shortcut=0.1.1=haa95532_6
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_0
  - python=3.10.18=h981015d_0
  - setuptools=78.1.1=py310haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - anytree==2.13.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - c3d==0.6.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - deep-sort-realtime==1.3.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - filterpy==1.4.5
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.75.1
      - h5py==3.14.0
      - idna==3.10
      - ipython==8.37.0
      - jax==0.6.2
      - jaxlib==0.6.2
      - jedi==0.19.2
      - keras==3.11.3
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - lxml==4.9.4
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mpl-interactions==0.24.2
      - namex==0.1.0
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - openvino==2025.3.0
      - openvino-telemetry==2025.2.0
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - patsy==1.0.1
      - pillow==11.3.0
      - pose2sim==0.10.13
      - prompt-toolkit==3.0.52
      - protobuf==6.32.1
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.5
      - rich==14.1.0
      - rtmlib==0.0.13
      - scipy==1.15.3
      - six==1.17.0
      - stack-data==0.6.3
      - statsmodels==0.14.5
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - toml==0.10.2
      - tomlkit==0.13.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - wrapt==1.17.3
prefix: C:\anaconda3\envs\Pose2Sim
